In [17]:
import numpy as np
np.set_printoptions(suppress=True)

def set_numpy_decimal_places(places, width=0):
    set_np = '{0:' + str(width) + '.' + str(places) + 'f}'
    np.set_printoptions(formatter={'float': lambda x: set_np.format(x)})
set_numpy_decimal_places(4)

In [18]:
A0 = np.array([[5, 1, 0],[9, 0, 1]])
b0 = np.array([1,2])
B0 = np.array([[5,1],[9,0]])
Binv0 = np.linalg.inv(B0)
print(Binv0)
p = np.matmul(Binv0, A0)
print(p)
x = np.matmul(Binv0, b0)
print(x)

[[0.0000 0.1111]
 [1.0000 -0.5556]]
[[1.0000 0.0000 0.1111]
 [0.0000 1.0000 -0.5556]]
[0.2222 -0.1111]


In [24]:
A1 = np.array([[1, 2, 2, 0, 0, 1, 0, 0, 0],
              [0, 2, 3, 0, 0, 0, 1, 0, 0],
              [1, 4, 0, 0, 0, 0, 0, 1, 0],
              [1/9, 4/9, 4/9, 0, 0, 0, 0, 0, 1],
              [1, -1, 0, 1, 0, 0, 0, 0, 0],
              [1, 0, -1, 0, 1, 0, 0, 0, 0]])
B1 = np.array([[1, 2, 2, 1, 0, 0],
              [0, 2, 3, 0, 1, 0],
              [1, 4, 0, 0, 0, 1],
              [1/9, 4/9, 4/9, 0, 0, 0],
              [1, -1, 0, 0, 0, 0],
              [1, 0, -1, 0, 0, 0]])
Binv1 = np.linalg.inv(B1)
print(Binv1)
b1 = np.array([1, 1, 1, 2/9, 0, 0])
p = np.matmul(Binv1, A1)
print(p)
# x = np.matmul(Binv1, b1)
# print(x)

[[0.0000 0.0000 0.0000 1.0000 0.4444 0.4444]
 [0.0000 -0.0000 -0.0000 1.0000 -0.5556 0.4444]
 [-0.0000 -0.0000 -0.0000 1.0000 0.4444 -0.5556]
 [1.0000 -0.0000 -0.0000 -5.0000 -0.2222 -0.2222]
 [0.0000 1.0000 0.0000 -5.0000 -0.2222 0.7778]
 [-0.0000 -0.0000 1.0000 -5.0000 1.7778 -2.2222]]
[[1.0000 -0.0000 -0.0000 0.4444 0.4444 0.0000 0.0000 0.0000 1.0000]
 [0.0000 1.0000 0.0000 -0.5556 0.4444 0.0000 0.0000 0.0000 1.0000]
 [-0.0000 0.0000 1.0000 0.4444 -0.5556 0.0000 0.0000 0.0000 1.0000]
 [-0.0000 -0.0000 -0.0000 -0.2222 -0.2222 1.0000 0.0000 0.0000 -5.0000]
 [0.0000 -0.0000 -0.0000 -0.2222 0.7778 0.0000 1.0000 0.0000 -5.0000]
 [-0.0000 -0.0000 -0.0000 1.7778 -2.2222 -0.0000 0.0000 1.0000 -5.0000]]


In [87]:
A1 = np.array([[1, 2, 2, 0, 0, 1, 0, 0, 0],
              [0, 2, 3, 0, 0, 0, 1, 0, 0],
              [1, 4, 0, 0, 0, 0, 0, 1, 0],
              [1, 4, 4, 0, 0, 0, 0, 0, 1],
              [1, -1, 0, 1, 0, 0, 0, 0, 0],
              [1, 0, -1, 0, 1, 0, 0, 0, 0]])
Binv1 = np.linalg.inv(B)
print(Binv1)


[[ 0.          0.          0.          0.11111111  0.44444444  0.44444444]
 [-0.         -0.         -0.          0.11111111 -0.55555556  0.44444444]
 [-0.         -0.         -0.          0.11111111  0.44444444 -0.55555556]
 [ 1.         -0.         -0.         -0.55555556 -0.22222222 -0.22222222]
 [ 0.          1.          0.         -0.55555556 -0.22222222  0.77777778]
 [-0.         -0.          1.         -0.55555556  1.77777778 -2.22222222]]


In [40]:
print(sum(i for i in Binv1[1]))

1.1102230246251565e-16
