In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [8]:
A0 = np.array([[5, 1, 0],[9, 0, 1]])
b0 = np.array([1,2])
B0 = np.array([[5,1],[9,0]])
Binv0 = np.linalg.inv(B0)
print(Binv0)
p = np.matmul(Binv0, A0)
print(p)
x = np.matmul(Binv0, b0)
print(x)

[[ 0.          0.11111111]
 [ 1.         -0.55555556]]
[[ 1.          0.          0.11111111]
 [ 0.          1.         -0.55555556]]
[ 0.22222222 -0.11111111]


In [34]:
B1 = np.array([[0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 1],
              [1, 0, 0, 0, 0, 0],
              [1, -1, 0, 0, 0, 0],
              [1, 0, -1, 0, 0, 0]])
Binv1 = np.linalg.inv(B1)
print(Binv1)

[[ 0.  0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -1. -0.]
 [-0. -0. -0.  1. -0. -1.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]]


In [20]:
B = np.array([[1, 2, 2, 1, 0, 0],
              [0, 2, 3, 0, 1, 0],
              [1, 4, 0, 0, 0, 1],
              [1, 4, 4, 0, 0, 0],
              [1, -1, 0, 0, 0, 0],
              [1, 0, -1, 0, 0, 0]])
Binv1 = np.linalg.inv(B)
print(Binv1)


[[ 0.          0.          0.          0.11111111  0.44444444  0.44444444]
 [-0.         -0.         -0.          0.11111111 -0.55555556  0.44444444]
 [-0.         -0.         -0.          0.11111111  0.44444444 -0.55555556]
 [ 1.         -0.         -0.         -0.55555556 -0.22222222 -0.22222222]
 [ 0.          1.          0.         -0.55555556 -0.22222222  0.77777778]
 [-0.         -0.          1.         -0.55555556  1.77777778 -2.22222222]]


In [40]:
print(sum(i for i in Binv1[1]))

1.1102230246251565e-16
